#!/bin/bash

set -e
set -u
set -E

DEFAULT_CONFIG="${HOME}/.singlekey"

# we only run if there is single-key-shortcut file
if  [[ -f ${DEFAULT_CONFIG} ]] ; then
    /usr/local/bin/singlekey -c $DEFAULT_CONFIG 
fi


